### ISSUE TITLE
我按照demo代码里的方法去实现，出现的错误，貌似是Json的错误

### ISSUE THREAD

**Issue by wubolinha** [Xiaofei-it/Hermes-IPC-Demo#1]
反复检查了几次，我的写法和demo一样，错误日志是：

E/JavaBinder: **\* Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                            java.lang.StackOverflowError
                                                                at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
。。。。。。。。。。。。。。。。。。。。。。

**Comment by Xiaofei-it** [comment]
你传的是什么数据类型？类里面有没有一个域指向同一个类的实例？比如：

```
class A {
    int i;
    A a;
}
```

传递链表就属于上面这种情况。这种情况目前Hermes不支持。

另外，这个例子比较老，对应的Hermes版本比较老。

**Comment by wubolinha** [comment]
我测试了下，获取自定义的对象类型，会爆出上面的错误。比如下面，如果不是返回string，就报错。
@MethodId("getdata")
    public   String  getdata(String key);

**Comment by Xiaofei-it** [comment]
函数要匹配，参数和返回值都要匹配，不匹配就会报错。情理上也说得通。
